const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
let now = 0, tick, captions = [];
const element = () => ({hidden:false,isConnected:true,setAttribute(){},removeAttribute(key){delete this[key];},after(caption){captions.push(caption);}});
const scope = {window:{}, Date:{now:()=>now}, document:{createElement:element},
  setInterval:fn=>{tick=fn;return 1;},clearInterval:()=>{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../frontend/wait-progress.js'),'utf8'), scope);
const bar = element(), t = (key, data) => key + (data ? JSON.stringify(data) : '');
const wait = scope.window.BorasukiWait;
wait.render(bar,null,true,t);
assert.equal(bar.hidden,false);
assert.equal(captions[0].hidden,true);
now=11000; tick();
assert.equal(bar.hidden,true,'no endless animation after ten seconds');
assert(captions[0].textContent.includes('wait.elapsed'));
assert(captions[0].textContent.includes('wait.eta_unknown'));
assert(captions[0].textContent.includes('wait.unmeasured'));
assert(!captions[0].textContent.includes('wait.percent'));
wait.render(bar,{completed:3,total:9,elapsed:11,updated_at:11,eta:12,eta_basis:'samples'},true,t);
assert.equal(bar.value,3); assert.equal(bar.max,9); assert.equal(bar.hidden,false);
assert(captions[0].textContent.includes('"percent":33'));
assert(captions[0].textContent.includes('wait.eta{'));
now=25000; tick();
assert(captions[0].textContent.includes('wait.eta_unknown'),'expired estimate never counts down to zero while still busy');
wait.render(bar,{completed:1500000000,total:3000000000,unit:'bytes',elapsed:15,updated_at:25,eta:20},true,t);
assert(captions[0].textContent.includes('wait.download'));
assert(captions[0].textContent.includes('1.50 GB'));
assert(captions[0].textContent.includes('3.00 GB'));
wait.render(bar,null,false,t);
assert.equal(bar.hidden,true); assert.equal(captions[0].hidden,true);
wait.render(bar,null,true,t);
assert.equal(bar.hidden,false,'a new operation starts fresh');
assert.equal(captions.length,1,'polling does not duplicate captions');
wait.render(bar,{completed:null,total:null,elapsed:30,updated_at:25,eta:70,eta_basis:'history'},true,t);
assert.equal(bar.hidden,true); assert.equal(captions[0].title,'wait.history_help');
assert(!captions[0].textContent.includes('wait.percent'),'history must not become synthetic percent');
console.log('Shared wait progress tests passed');
